### ISSUE TITLE
Items without lore & with NBT

### ISSUE THREAD

**Issue by SJ-Tom** [jandie1505/LobbySelector#1] opened 2024-01-21 18:12 UTC
Is it possible to provide an option for disabling the lore text because they are not fancy, and the service name is already in the name. I think it is possible to split the name that the plugins knows that this item is for server id x. And it would be cool if you can add NBT support for the items that the custom model data can be changed.

**Comment by jandie1505** [comment] 2024-01-21 20:37
I moved the service name to the persistent data container where nobody can see it.
I also added support for changing lore, enchant status and custom model data.

I don't know yet whether I will add full NBT support, but probably not in the next few weeks.

Here is the new release:
https://github.com/jandie1505/LobbySelector/releases/tag/v1.1

You need to update your config as described on the releases page when you update the plugin.

**Comment by SJ-Tom** [comment] 2024-01-21 21:06
Thanks for the fast update. I'll take a look at this version

**Comment by SJ-Tom** [comment] 2024-01-22 10:21
I have now updated the plugin and deleted the plugin folder to generate the new config, but now I can no longer click on any items. So I am no longer sent to the server

**Comment by jandie1505** [comment] 2024-01-22 11:08
Since I could not reproduce this error, could you please provide more information?

Which version of CloudNet and Spigot are you using?
Are there any exceptions in the console thrown by my plugin (especially when clicking on the items or opening the inventory)?
Do you use other plugins that use inventories so that I can test my plugin together with these plugins?

Also, what do you mean with you can no longer click on items? Does the inventory open? If yes, is the inventory click event cancelled (it is when you can't pick up the item from the inventory)?

**Comment by SJ-Tom** [comment] 2024-01-22 12:35
I have tested it without a plugin so that no other plugin affects the inventory move event, my cloudnet is on the latest release candidate 9 and for the server version I am currently using purpur build 2112. My console shows no errors and nothing has happened ingame either.

**Comment by jandie1505** [comment] 2024-01-22 18:55
Are you in the player list of `/cloud players online` while you are on the network?

**Comment by SJ-Tom** [comment] 2024-01-22 19:17
No, I am not.

**Comment by jandie1505** [comment] 2024-01-22 19:25
Ok than that is the problem.
Since my plugin uses the CloudNet API to move players between servers, a player cannot be moved if CloudNet doesn't know that the player is online. But I haven't changed the part about moving players between servers, so the old version shouldn't work anymore either.
Are you using ViaVersion and are you online with a game version which is higher than the server version?

**Comment by SJ-Tom** [comment] 2024-01-22 19:26
Yes, I am using ViaVersion but the Serverversion of Backend is 1.20.4, so there is no player online with a newer version as the Server Version.

**Comment by jandie1505** [comment] 2024-01-22 19:37
I had a similar error when I was still using RC9.
I had the server on 1.20.1, but with ViaVersion people could join even with higher versions. If a player joined with a higher version, he did not appear in the cloudnet playerlist.

Maybe it has to do with the version, because CloudNet RC9 only officially supports up to 1.20.1.
I had created an issue at CloudNet at that time, the error should then be fixed in RC10. It is currently not officially released, so if you want to get these changes, you need to switch to `nightly`.

But I don't know if it then works because the highest supported version of `nightly` is 1.20.2. But since the bug does not occur on a 1.20.2 server with ViaVersion, I assume that it should work then.

Link to the issue: https://github.com/CloudNetService/CloudNet-v3/issues/1310

**Comment by SJ-Tom** [comment] 2024-01-22 19:40
Okay I'll see if it works in the nightly, a pr for 1.20.4 (https://github.com/CloudNetService/CloudNet-v3/pull/1351) exists but is not yet merged

**Comment by SJ-Tom** [comment] 2024-01-22 19:58
The plugin works perfectly on Nightly

**Closed as completed** 2024-01-23 11:29 UTC
Labels: enhancement
